name: Python package build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Upgrade pip, setuptools, wheel, and build
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel build

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run build
        run: |
          python -m build
